#!/bin/bash

[[ $# -eq 2 ]] || {
  echo "Error, need 2 args: bundle name, and bundle extension (b83/b84)"; exit 1;
}

bname=$1
bext=$2

[[ "$bext" =~ ^b8[34]$ ]] || {
  echo "Error: extension must be b83 or b84"; exit 1;
}

[ -d ~/shared/ti/app ] && cd ~/shared/ti/app || cd shared/ti/app || exit 1

convbin -j 8x -k "${bext}" \
$(find . -maxdepth 1 -name 'AppIns[0-9]*.8xv' | sort -V | xargs printf -- '-i %s ') \
-i ../arTIfiCE.8xp -i ../INST.8xp \
-o "${bname}.${bext}"
